/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a0d1bc",
        "surface-container-high": "#deebe1",
        "surface-container": "#e4f1e7",
        "primary-fixed": "#bcedd8",
        "error": "#ba1a1a",
        "outline-variant": "#c0c8c3",
        "surface-tint": "#396756",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#404944",
        "secondary": "#2a694f",
        "inverse-on-surface": "#e7f4ea",
        "on-secondary-fixed-variant": "#095138",
        "background": "#f0fdf2",
        "on-tertiary-container": "#c28581",
        "on-surface": "#131e18",
        "surface-container-highest": "#d9e6dc",
        "border-subtle": "#e5e7eb",
        "bg-base": "#ffffff",
        "on-primary-fixed-variant": "#204f3f",
        "on-tertiary-fixed-variant": "#693937",
        "on-secondary-fixed": "#002114",
        "inverse-primary": "#a0d1bc",
        "secondary-container": "#aff1ce",
        "surface-container-low": "#eaf7ec",
        "success": "#22c55e",
        "surface": "#f0fdf2",
        "outline": "#717974",
        "tertiary-container": "#4b211f",
        "on-secondary-container": "#317054",
        "on-secondary": "#ffffff",
        "text-secondary": "#6b7280",
        "on-background": "#131e18",
        "on-primary-fixed": "#002117",
        "on-error-container": "#93000a",
        "primary": "#001e15",
        "tertiary": "#310d0c",
        "on-primary-container": "#709f8c",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#f9b6b1",
        "bg-section": "#f4f6f4",
        "surface-dim": "#d0ddd3",
        "on-primary": "#ffffff",
        "surface-variant": "#d9e6dc",
        "inverse-surface": "#28332c",
        "secondary-fixed": "#aff1ce",
        "tertiary-fixed": "#ffdad7",
        "primary-container": "#003527",
        "surface-bright": "#f0fdf2",
        "on-tertiary-fixed": "#340f0e",
        "secondary-fixed-dim": "#93d4b3",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "1.5rem",
        "margin-page": "2rem",
        "stack-sm": "0.5rem",
        "stack-lg": "2rem",
        "stack-md": "1rem"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "1", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
