const fs = require('fs');
let content = fs.readFileSync('frontend/app/bots/[id]/page.tsx', 'utf8');
const replacements = {
  'Подключить первый канал': 'Connect first channel',
  'Подключен': 'Connected',
  'На паузе': 'Paused',
  'Управление приёмом сообщений': 'Message Reception Control',
  'Пауза': 'Pause',
  'Старт': 'Start',
  'Вы уверены, что хотите отключить и удалить этот канал связи?': 'Are you sure you want to disconnect and delete this communication channel?',
  'Удалить канал': 'Delete Channel',
  'Выбор платформы': 'Platform Selection',
  'Подключение Telegram': 'Telegram Connection',
  'Подключение WhatsApp': 'WhatsApp Connection',
  'Выберите мессенджер для интеграции': 'Select messenger for integration',
  'Шаг подключения бота к вашему аккаунту': 'Step to connect bot to your account',
  'Идеально для официальных ботов, рассылок, кнопок и каналов.': 'Ideal for official bots, broadcasts, buttons, and channels.',
  'Прямая работа с личными номерами. Быстрый старт через сканирование QR.': 'Direct work with personal numbers. Quick start via QR scanning.',
  'Тестовое подключение Instagram канала по API Meta.': 'Test connection of Instagram channel via Meta API.',
  'Инструкция по подключению Telegram': 'Instructions for connecting Telegram',
  'Откройте Telegram и перейдите к официальному боту': 'Open Telegram and go to the official bot',
  'Отправьте ему команду': 'Send him the command',
  'для создания нового бота': 'to create a new bot',
  'Задайте боту имя и уникальный юзернейм (оканчивающийся на': 'Give the bot a name and a unique username (ending in',
  'Скопируйте полученный **API Token** и введите его в текстовое поле ниже': 'Copy the received **API Token** and enter it in the text field below',
  'Токен бота (API HTTP Token)': 'Bot Token (API HTTP Token)',
  'Пример: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11': 'Example: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11',
  'Неверный токен бота или ошибка подключения': 'Invalid bot token or connection error',
  'Подключение канала...': 'Connecting channel...',
  'Подключить Telegram Bot': 'Connect Telegram Bot',
  'Подключение Instagram API': 'Instagram API Connection',
  'Введите настройки Meta API для подключения Instagram аккаунта (Page Access Token).': 'Enter Meta API settings to connect Instagram account (Page Access Token).',
  'Неверный токен или ошибка подключения': 'Invalid token or connection error',
  'Подключить Instagram': 'Connect Instagram',
  'Генерация QR-кода': 'QR Code Generation',
  'Для подключения WhatsApp сессии мы сгенерируем защищенный веб-интерфейс QR-кода.': 'To connect WhatsApp session, we will generate a secure QR code web interface.',
  'Сгенерировать QR-код': 'Generate QR code',
  'Как отсканировать QR-код': 'How to scan QR code',
  'Откройте **WhatsApp** на вашем телефоне': 'Open **WhatsApp** on your phone',
  'Перейдите в **Меню** (три точки) или **Настройки** → **Связанные устройства**': 'Go to **Menu** (three dots) or **Settings** → **Linked Devices**',
  'Нажмите кнопку **Привязка устройства** и наведите камеру телефона на экран': 'Click the **Link a Device** button and point your phone camera at the screen',
  '🔔 **Важно:** Не закрывайте страницу до завершения сканирования. Сессия подключится автоматически.': '🔔 **Important:** Do not close the page until scanning is complete. The session will connect automatically.',
  'Ожидание подключения с телефона...': 'Waiting for connection from phone...',
  'Скрытый номер': 'Hidden number',
  'Включить ИИ': 'Turn on AI',
  'Отключить ИИ': 'Turn off AI',
  "Направьте бота (например: 'Будь вежливее')": "Direct the bot (e.g. 'Be more polite')",
  'Взаимодействие с AI Мозгом': 'Interaction with AI Brain',
  'Общайтесь с агентом напрямую для настройки его поведения и базы знаний.': 'Communicate with the agent directly to configure its behavior and knowledge base.',
  'Напишите, что нужно изменить в поведении бота.': 'Write what needs to be changed in the bots behavior.',
  'ИИ думает...': 'AI is thinking...',
  "Например: 'Будь более вежливым' или 'Добавь в базу, что мы не работаем по выходным'": "Example: 'Be more polite' or 'Add to the database that we do not work on weekends'",
  'Отправить': 'Send',
  'Вопрос': 'Question',
  'Ответ': 'Answer',
  'Добавить вопрос': 'Add question',
  'Название (напр. Наш сайт)': 'Name (e.g. Our website)',
  'Добавить ссылку': 'Add link',
  'Введите информацию...': 'Enter information...',
  'Дополнительный факт:': 'Additional fact:',
  'Добавить': 'Add',
  'Помощник UP-CHAT': 'UP-CHAT Assistant',
  'Шаг': 'Step',
  'из 5': 'of 5',
  'Ваш ИИ-ассистент успешно создан! 🎉 Теперь давайте подключим каналы связи (Telegram или WhatsApp), чтобы он мог общаться с клиентами.': 'Your AI assistant has been successfully created! 🎉 Now lets connect communication channels (Telegram or WhatsApp) so it can chat with clients.',
  'Отлично! После подключения каналов обязательно настройте базу знаний во вкладке AI Brain. 🧠 Вы можете загрузить сюда файлы, написать описание компании и товаров, добавить полезные ссылки и FAQ. Это научит ассистента вашему продукту.': 'Great! After connecting channels, be sure to set up the knowledge base in the AI Brain tab. 🧠 You can upload files here, write a description of the company and products, add useful links and FAQ. This will teach the assistant about your product.',
  'Вкладка Диалоги 💬 — это ваш живой пульт управления. Здесь отображаются все переписки в реальном времени. В любой момент вы можете перехватить диалог у бота и ответить клиенту лично.': 'The Dialogues tab 💬 is your live control panel. All correspondence is displayed here in real time. At any time you can intercept the dialogue from the bot and answer the client personally.',
  'Вкладка Конфигурация ⚙️ позволяет настраивать тон общения, цели бота, собираемые данные о лидах и тестировать ассистента в песочнице перед публикацией.': 'The Configuration tab ⚙️ allows you to configure the tone of communication, bot goals, collected lead data, and test the assistant in the sandbox before publishing.',
  'Вы готовы к запуску! 🚀 Теперь вы можете подключить Telegram или WhatsApp и протестировать работу вашего бота. Если возникнут вопросы — наша поддержка всегда на связи.': 'You are ready to launch! 🚀 Now you can connect Telegram or WhatsApp and test your bot. If you have any questions - our support is always in touch.',
  'Завершить': 'Finish',
  'Далее →': 'Next →'
};
for (const [ru, en] of Object.entries(replacements)) {
  content = content.split(ru).join(en);
}
fs.writeFileSync('frontend/app/bots/[id]/page.tsx', content);
console.log('Done');
